// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: destination.proto

package destination

import (
	node "github.com/blahcdn/proto/node"
	types "github.com/blahcdn/proto/types"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SusType int32

const (
	SusType_NOT_SUS   SusType = 0
	SusType_RATELIMIT SusType = 1
	SusType_ROBOT     SusType = 2
)

// Enum value maps for SusType.
var (
	SusType_name = map[int32]string{
		0: "NOT_SUS",
		1: "RATELIMIT",
		2: "ROBOT",
	}
	SusType_value = map[string]int32{
		"NOT_SUS":   0,
		"RATELIMIT": 1,
		"ROBOT":     2,
	}
)

func (x SusType) Enum() *SusType {
	p := new(SusType)
	*p = x
	return p
}

func (x SusType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SusType) Descriptor() protoreflect.EnumDescriptor {
	return file_destination_proto_enumTypes[0].Descriptor()
}

func (SusType) Type() protoreflect.EnumType {
	return &file_destination_proto_enumTypes[0]
}

func (x SusType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SusType.Descriptor instead.
func (SusType) EnumDescriptor() ([]byte, []int) {
	return file_destination_proto_rawDescGZIP(), []int{0}
}

type GetDestination struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Authority *types.Authority `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	Headermap []*HeaderType    `protobuf:"bytes,2,rep,name=headermap,proto3" json:"headermap,omitempty"`
}

func (x *GetDestination) Reset() {
	*x = GetDestination{}
	if protoimpl.UnsafeEnabled {
		mi := &file_destination_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDestination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDestination) ProtoMessage() {}

func (x *GetDestination) ProtoReflect() protoreflect.Message {
	mi := &file_destination_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDestination.ProtoReflect.Descriptor instead.
func (*GetDestination) Descriptor() ([]byte, []int) {
	return file_destination_proto_rawDescGZIP(), []int{0}
}

func (x *GetDestination) GetAuthority() *types.Authority {
	if x != nil {
		return x.Authority
	}
	return nil
}

func (x *GetDestination) GetHeadermap() []*HeaderType {
	if x != nil {
		return x.Headermap
	}
	return nil
}

type DestinationRoute struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sus     SusType          `protobuf:"varint,1,opt,name=sus,proto3,enum=blahcdn.destination.SusType" json:"sus,omitempty"` // is the client suspicious? if so, block it or check if client is a bot
	HopNode []*node.NodeInfo `protobuf:"bytes,2,rep,name=hopNode,proto3" json:"hopNode,omitempty"`                           // list of nodes to hop to in order to reach origin
}

func (x *DestinationRoute) Reset() {
	*x = DestinationRoute{}
	if protoimpl.UnsafeEnabled {
		mi := &file_destination_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DestinationRoute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestinationRoute) ProtoMessage() {}

func (x *DestinationRoute) ProtoReflect() protoreflect.Message {
	mi := &file_destination_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestinationRoute.ProtoReflect.Descriptor instead.
func (*DestinationRoute) Descriptor() ([]byte, []int) {
	return file_destination_proto_rawDescGZIP(), []int{1}
}

func (x *DestinationRoute) GetSus() SusType {
	if x != nil {
		return x.Sus
	}
	return SusType_NOT_SUS
}

func (x *DestinationRoute) GetHopNode() []*node.NodeInfo {
	if x != nil {
		return x.HopNode
	}
	return nil
}

type HeaderType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *HeaderType) Reset() {
	*x = HeaderType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_destination_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HeaderType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeaderType) ProtoMessage() {}

func (x *HeaderType) ProtoReflect() protoreflect.Message {
	mi := &file_destination_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeaderType.ProtoReflect.Descriptor instead.
func (*HeaderType) Descriptor() ([]byte, []int) {
	return file_destination_proto_rawDescGZIP(), []int{2}
}

func (x *HeaderType) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *HeaderType) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_destination_proto protoreflect.FileDescriptor

var file_destination_proto_rawDesc = []byte{
	0x0a, 0x11, 0x64, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x13, 0x62, 0x6c, 0x61, 0x68, 0x63, 0x64, 0x6e, 0x2e, 0x64, 0x65, 0x73,
	0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x0f, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72,
	0x69, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0a, 0x6e, 0x6f, 0x64, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x87, 0x01, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x44, 0x65, 0x73,
	0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x36, 0x0a, 0x09, 0x61, 0x75, 0x74, 0x68,
	0x6f, 0x72, 0x69, 0x74, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x62, 0x6c,
	0x61, 0x68, 0x63, 0x64, 0x6e, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x41, 0x75, 0x74, 0x68,
	0x6f, 0x72, 0x69, 0x74, 0x79, 0x52, 0x09, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x74, 0x79,
	0x12, 0x3d, 0x0a, 0x09, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x6d, 0x61, 0x70, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x62, 0x6c, 0x61, 0x68, 0x63, 0x64, 0x6e, 0x2e, 0x64, 0x65,
	0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x54, 0x79, 0x70, 0x65, 0x52, 0x09, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x6d, 0x61, 0x70, 0x22,
	0x74, 0x0a, 0x10, 0x44, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x6f,
	0x75, 0x74, 0x65, 0x12, 0x2e, 0x0a, 0x03, 0x73, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x1c, 0x2e, 0x62, 0x6c, 0x61, 0x68, 0x63, 0x64, 0x6e, 0x2e, 0x64, 0x65, 0x73, 0x74, 0x69,
	0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x53, 0x75, 0x73, 0x54, 0x79, 0x70, 0x65, 0x52, 0x03,
	0x73, 0x75, 0x73, 0x12, 0x30, 0x0a, 0x07, 0x68, 0x6f, 0x70, 0x4e, 0x6f, 0x64, 0x65, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x62, 0x6c, 0x61, 0x68, 0x63, 0x64, 0x6e, 0x2e, 0x6e,
	0x6f, 0x64, 0x65, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x07, 0x68, 0x6f,
	0x70, 0x4e, 0x6f, 0x64, 0x65, 0x22, 0x34, 0x0a, 0x0a, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x2a, 0x30, 0x0a, 0x07, 0x53,
	0x75, 0x73, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x4e, 0x4f, 0x54, 0x5f, 0x53, 0x55,
	0x53, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x52, 0x41, 0x54, 0x45, 0x4c, 0x49, 0x4d, 0x49, 0x54,
	0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x52, 0x4f, 0x42, 0x4f, 0x54, 0x10, 0x02, 0x32, 0x60, 0x0a,
	0x0b, 0x44, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x51, 0x0a, 0x03,
	0x47, 0x65, 0x74, 0x12, 0x23, 0x2e, 0x62, 0x6c, 0x61, 0x68, 0x63, 0x64, 0x6e, 0x2e, 0x64, 0x65,
	0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x65, 0x73,
	0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x25, 0x2e, 0x62, 0x6c, 0x61, 0x68, 0x63,
	0x64, 0x6e, 0x2e, 0x64, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x44,
	0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x42,
	0x26, 0x5a, 0x24, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x62, 0x6c,
	0x61, 0x68, 0x63, 0x64, 0x6e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x64, 0x65, 0x73, 0x74,
	0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_destination_proto_rawDescOnce sync.Once
	file_destination_proto_rawDescData = file_destination_proto_rawDesc
)

func file_destination_proto_rawDescGZIP() []byte {
	file_destination_proto_rawDescOnce.Do(func() {
		file_destination_proto_rawDescData = protoimpl.X.CompressGZIP(file_destination_proto_rawDescData)
	})
	return file_destination_proto_rawDescData
}

var file_destination_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_destination_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_destination_proto_goTypes = []interface{}{
	(SusType)(0),             // 0: blahcdn.destination.SusType
	(*GetDestination)(nil),   // 1: blahcdn.destination.GetDestination
	(*DestinationRoute)(nil), // 2: blahcdn.destination.DestinationRoute
	(*HeaderType)(nil),       // 3: blahcdn.destination.HeaderType
	(*types.Authority)(nil),  // 4: blahcdn.types.Authority
	(*node.NodeInfo)(nil),    // 5: blahcdn.node.NodeInfo
}
var file_destination_proto_depIdxs = []int32{
	4, // 0: blahcdn.destination.GetDestination.authority:type_name -> blahcdn.types.Authority
	3, // 1: blahcdn.destination.GetDestination.headermap:type_name -> blahcdn.destination.HeaderType
	0, // 2: blahcdn.destination.DestinationRoute.sus:type_name -> blahcdn.destination.SusType
	5, // 3: blahcdn.destination.DestinationRoute.hopNode:type_name -> blahcdn.node.NodeInfo
	1, // 4: blahcdn.destination.Destination.Get:input_type -> blahcdn.destination.GetDestination
	2, // 5: blahcdn.destination.Destination.Get:output_type -> blahcdn.destination.DestinationRoute
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_destination_proto_init() }
func file_destination_proto_init() {
	if File_destination_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_destination_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDestination); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_destination_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DestinationRoute); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_destination_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HeaderType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_destination_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_destination_proto_goTypes,
		DependencyIndexes: file_destination_proto_depIdxs,
		EnumInfos:         file_destination_proto_enumTypes,
		MessageInfos:      file_destination_proto_msgTypes,
	}.Build()
	File_destination_proto = out.File
	file_destination_proto_rawDesc = nil
	file_destination_proto_goTypes = nil
	file_destination_proto_depIdxs = nil
}
